(ns com.amazonaws.retry.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.amazonaws.retry.ClockSkewAdjuster$AdjustmentRequest])
(require '[com.amazonaws.retry.ClockSkewAdjuster$ClockSkewAdjustment])
(require '[com.amazonaws.retry.ClockSkewAdjuster])
(require '[com.amazonaws.retry.PredefinedBackoffStrategies$EqualJitterBackoffStrategy])
(require '[com.amazonaws.retry.PredefinedBackoffStrategies$ExponentialBackoffStrategy])
(require '[com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy])
(require '[com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy])
(require '[com.amazonaws.retry.PredefinedBackoffStrategies])
(require '[com.amazonaws.retry.PredefinedRetryPolicies$SDKDefaultRetryCondition])
(require '[com.amazonaws.retry.PredefinedRetryPolicies])
(require '[com.amazonaws.retry.RetryPolicy$BackoffStrategy])
(require '[com.amazonaws.retry.RetryPolicy$RetryCondition])
(require '[com.amazonaws.retry.RetryPolicy])
(require '[com.amazonaws.retry.RetryPolicyAdapter])
(require '[com.amazonaws.retry.RetryUtils])
(require '[com.amazonaws.retry.V2CompatibleBackoffStrategy])
