(ns com.amazonaws.services.dynamodbv2.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.amazonaws.services.dynamodbv2.AbstractAmazonDynamoDB])
(require '[com.amazonaws.services.dynamodbv2.AbstractAmazonDynamoDBAsync])
(require '[com.amazonaws.services.dynamodbv2.AbstractAmazonDynamoDBStreams])
(require '[com.amazonaws.services.dynamodbv2.AbstractAmazonDynamoDBStreamsAsync])
(require '[com.amazonaws.services.dynamodbv2.AmazonDynamoDB])
(require '[com.amazonaws.services.dynamodbv2.AmazonDynamoDBAsync])
(require '[com.amazonaws.services.dynamodbv2.AmazonDynamoDBAsyncClient])
(require '[com.amazonaws.services.dynamodbv2.AmazonDynamoDBAsyncClientBuilder])
(require '[com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient])
(require '[com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder])
(require '[com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreams])
(require '[com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsAsync])
(require '[com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsAsyncClient])
(require '[com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsAsyncClientBuilder])
(require '[com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsClient])
(require '[com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsClientBuilder])
