(ns com.amazonaws.handlers.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.amazonaws.handlers.AbstractRequestHandler])
(require '[com.amazonaws.handlers.AsyncHandler])
(require '[com.amazonaws.handlers.CredentialsRequestHandler])
(require '[com.amazonaws.handlers.HandlerAfterAttemptContext$HandlerAfterAttemptContextBuilder])
(require '[com.amazonaws.handlers.HandlerAfterAttemptContext])
(require '[com.amazonaws.handlers.HandlerBeforeAttemptContext$HandlerBeforeAttemptContextBuilder])
(require '[com.amazonaws.handlers.HandlerBeforeAttemptContext])
(require '[com.amazonaws.handlers.HandlerChainFactory])
(require '[com.amazonaws.handlers.HandlerContextKey])
(require '[com.amazonaws.handlers.IRequestHandler2])
(require '[com.amazonaws.handlers.RequestHandler])
(require '[com.amazonaws.handlers.RequestHandler2])
(require '[com.amazonaws.handlers.StackedRequestHandler])
