(ns com.amazonaws.regions.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.amazonaws.regions.AbstractRegionMetadataProvider])
(require '[com.amazonaws.regions.AwsEnvVarOverrideRegionProvider])
(require '[com.amazonaws.regions.AwsProfileRegionProvider])
(require '[com.amazonaws.regions.AwsRegionProvider])
(require '[com.amazonaws.regions.AwsRegionProviderChain])
(require '[com.amazonaws.regions.AwsSystemPropertyRegionProvider])
(require '[com.amazonaws.regions.DefaultAwsRegionProviderChain])
(require '[com.amazonaws.regions.InMemoryRegionImpl])
(require '[com.amazonaws.regions.InMemoryRegionsProvider])
(require '[com.amazonaws.regions.InstanceMetadataRegionProvider])
(require '[com.amazonaws.regions.LegacyRegionXmlLoadUtils])
(require '[com.amazonaws.regions.LegacyRegionXmlMetadataBuilder])
(require '[com.amazonaws.regions.Region])
(require '[com.amazonaws.regions.RegionImpl])
(require '[com.amazonaws.regions.RegionMetadata])
(require '[com.amazonaws.regions.RegionMetadataFactory])
(require '[com.amazonaws.regions.RegionMetadataParser])
(require '[com.amazonaws.regions.RegionMetadataProvider])
(require '[com.amazonaws.regions.RegionUtils])
(require '[com.amazonaws.regions.Regions])
(require '[com.amazonaws.regions.ServiceAbbreviations])
