(ns com.amazonaws.metrics.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.amazonaws.metrics.AwsSdkMetrics])
(require '[com.amazonaws.metrics.ByteThroughputProvider])
(require '[com.amazonaws.metrics.MetricAdmin])
(require '[com.amazonaws.metrics.MetricAdminMBean])
(require '[com.amazonaws.metrics.MetricCollector$Factory])
(require '[com.amazonaws.metrics.MetricCollector])
(require '[com.amazonaws.metrics.MetricFilterInputStream])
(require '[com.amazonaws.metrics.MetricInputStreamEntity])
(require '[com.amazonaws.metrics.MetricType])
(require '[com.amazonaws.metrics.NoOpClassForJavadocGeneration])
(require '[com.amazonaws.metrics.RequestMetricCollector$Factory])
(require '[com.amazonaws.metrics.RequestMetricCollector])
(require '[com.amazonaws.metrics.RequestMetricType])
(require '[com.amazonaws.metrics.ServiceLatencyProvider])
(require '[com.amazonaws.metrics.ServiceMetricCollector$Factory])
(require '[com.amazonaws.metrics.ServiceMetricCollector])
(require '[com.amazonaws.metrics.ServiceMetricType])
(require '[com.amazonaws.metrics.SimpleMetricType])
(require '[com.amazonaws.metrics.SimpleServiceMetricType])
(require '[com.amazonaws.metrics.SimpleThroughputMetricType])
(require '[com.amazonaws.metrics.ThroughputMetricType])
