(ns com.amazonaws.services.waf.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.amazonaws.services.waf.AWSWAF])
(require '[com.amazonaws.services.waf.AWSWAFAsync])
(require '[com.amazonaws.services.waf.AWSWAFAsyncClient])
(require '[com.amazonaws.services.waf.AWSWAFAsyncClientBuilder])
(require '[com.amazonaws.services.waf.AWSWAFClient])
(require '[com.amazonaws.services.waf.AWSWAFClientBuilder])
(require '[com.amazonaws.services.waf.AWSWAFRegional])
(require '[com.amazonaws.services.waf.AWSWAFRegionalAsync])
(require '[com.amazonaws.services.waf.AWSWAFRegionalAsyncClient])
(require '[com.amazonaws.services.waf.AWSWAFRegionalAsyncClientBuilder])
(require '[com.amazonaws.services.waf.AWSWAFRegionalClient])
(require '[com.amazonaws.services.waf.AWSWAFRegionalClientBuilder])
(require '[com.amazonaws.services.waf.AbstractAWSWAF])
(require '[com.amazonaws.services.waf.AbstractAWSWAFAsync])
(require '[com.amazonaws.services.waf.AbstractAWSWAFRegional])
(require '[com.amazonaws.services.waf.AbstractAWSWAFRegionalAsync])
