(ns com.amazonaws.services.cloudfront.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.amazonaws.services.cloudfront.AbstractAmazonCloudFront])
(require '[com.amazonaws.services.cloudfront.AbstractAmazonCloudFrontAsync])
(require '[com.amazonaws.services.cloudfront.AmazonCloudFront])
(require '[com.amazonaws.services.cloudfront.AmazonCloudFrontAsync])
(require '[com.amazonaws.services.cloudfront.AmazonCloudFrontAsyncClient])
(require '[com.amazonaws.services.cloudfront.AmazonCloudFrontAsyncClientBuilder])
(require '[com.amazonaws.services.cloudfront.AmazonCloudFrontClient])
(require '[com.amazonaws.services.cloudfront.AmazonCloudFrontClientBuilder])
(require '[com.amazonaws.services.cloudfront.CloudFrontCookieSigner$CookiesForCannedPolicy])
(require '[com.amazonaws.services.cloudfront.CloudFrontCookieSigner$CookiesForCustomPolicy])
(require '[com.amazonaws.services.cloudfront.CloudFrontCookieSigner$SignedCookies])
(require '[com.amazonaws.services.cloudfront.CloudFrontCookieSigner])
(require '[com.amazonaws.services.cloudfront.CloudFrontUrlSigner])
