(ns com.amazonaws.services.workdocs.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.amazonaws.services.workdocs.AbstractAmazonWorkDocs])
(require '[com.amazonaws.services.workdocs.AbstractAmazonWorkDocsAsync])
(require '[com.amazonaws.services.workdocs.AmazonWorkDocs])
(require '[com.amazonaws.services.workdocs.AmazonWorkDocsAsync])
(require '[com.amazonaws.services.workdocs.AmazonWorkDocsAsyncClient])
(require '[com.amazonaws.services.workdocs.AmazonWorkDocsAsyncClientBuilder])
(require '[com.amazonaws.services.workdocs.AmazonWorkDocsClient])
(require '[com.amazonaws.services.workdocs.AmazonWorkDocsClientBuilder])
(require '[com.amazonaws.services.workdocs.ContentManager])
(require '[com.amazonaws.services.workdocs.ContentManagerAsync])
(require '[com.amazonaws.services.workdocs.ContentManagerAsyncBuilder])
(require '[com.amazonaws.services.workdocs.ContentManagerBuilder])
(require '[com.amazonaws.services.workdocs.GetDocumentStreamRequest])
(require '[com.amazonaws.services.workdocs.GetDocumentStreamResult])
(require '[com.amazonaws.services.workdocs.UploadDocumentStreamRequest])
(require '[com.amazonaws.services.workdocs.UploadDocumentStreamResult])
