(ns com.amazonaws.http.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.amazonaws.http.AmazonHttpClient$Builder])
(require '[com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilder])
(require '[com.amazonaws.http.AmazonHttpClient])
(require '[com.amazonaws.http.DefaultErrorResponseHandler])
(require '[com.amazonaws.http.DelegatingDnsResolver])
(require '[com.amazonaws.http.ExecutionContext$Builder])
(require '[com.amazonaws.http.ExecutionContext])
(require '[com.amazonaws.http.HttpMethodName])
(require '[com.amazonaws.http.HttpResponse])
(require '[com.amazonaws.http.HttpResponseHandler])
(require '[com.amazonaws.http.IdleConnectionReaper])
(require '[com.amazonaws.http.JsonErrorResponseHandler])
(require '[com.amazonaws.http.JsonResponseHandler])
(require '[com.amazonaws.http.RepeatableInputStreamRequestEntity])
(require '[com.amazonaws.http.SdkHttpMetadata])
(require '[com.amazonaws.http.StaxResponseHandler])
